# config/packages/knp_paginator.yaml

knp_paginator:
    page_range: 6
    default_options:
        sort_field_name: 'sort'
        sort_direction_name: 'direction'
        filter_field_name: 'filterField'
        filter_value_name: 'filterValue'
        distinct: true
    template:
        pagination: '@KnpPaginator/Pagination/bootstrap_v5_pagination.html.twig'
